# Generated by Django 5.2.1 on 2025-05-20 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200, verbose_name='Host')),
                ('port', models.PositiveIntegerField(default=1883, verbose_name='Port')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Password')),
                ('topic', models.CharField(blank=True, max_length=20, verbose_name='Topic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=20, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=20, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
