# Generated by Django 5.2.1 on 2025-05-27 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamp_status', models.BooleanField(default=False, verbose_name='Lamp Status')),
                ('control_mode', models.CharField(choices=[('manual', 'Mode 1 - Manual'), ('pir', 'Mode 2 - PIR Motion'), ('photoresistor', 'Mode 3 - Photoresistor')], default='manual', max_length=20, verbose_name='Control Mode')),
                ('photoresistor_value', models.IntegerField(default=0, verbose_name='Photoresistor Value')),
                ('pir_motion_detected', models.BooleanField(default=False, verbose_name='PIR Motion Detected')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
